# Generated by Django 5.2.7 on 2025-10-24 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('idadministradores', models.IntegerField(primary_key=True, serialize=False)),
                ('contraseña', models.IntegerField()),
                ('nombre', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('correo_electronico', models.CharField(max_length=45)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('idauditoria', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('idmedico', models.IntegerField(primary_key=True, serialize=False)),
                ('contrasena', models.IntegerField()),
                ('nombre', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('especialidad', models.CharField(max_length=45)),
                ('correo_electronico', models.EmailField(max_length=45)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idpaciente', models.IntegerField(primary_key=True, serialize=False)),
                ('contrasena', models.IntegerField()),
                ('nombre', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('correo_electronico', models.CharField(max_length=45)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('idhistorial', models.AutoField(primary_key=True, serialize=False)),
                ('recetas_json', models.JSONField(blank=True, default=list)),
                ('fecha', models.DateField(auto_now=True)),
                ('idpaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='CitaMedica',
            fields=[
                ('idcitas_medicas', models.AutoField(primary_key=True, serialize=False)),
                ('especialidad', models.CharField(max_length=45)),
                ('fecha', models.DateField()),
                ('hora', models.CharField(max_length=45)),
                ('estado_cita', models.CharField(default='Pendiente', max_length=45)),
                ('idmedico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.medico')),
                ('idpaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='RecetaMedica',
            fields=[
                ('idrecetas_medicas', models.AutoField(primary_key=True, serialize=False)),
                ('diagnostico', models.CharField(max_length=300)),
                ('medicamentos', models.CharField(max_length=45)),
                ('indicaciones', models.CharField(max_length=45)),
                ('idcitas_medicas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.citamedica')),
                ('idmedico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.medico')),
                ('idpaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.paciente')),
            ],
        ),
    ]
